# ==========================================
# Configuração de Servidor DNS com Unbound !
# ==========================================

server:
	# Configuração da Rede ===
	interface: 0.0.0.0

	access-control: 172.31.0.0/16 allow
	access-control: 192.168.1.0/24 allow
	access-control: 127.0.0.0/8 allow
	access-control: 0.0.0.0/0 deny

	port: 53

	do-udp: yes
	do-tcp: yes
	do-ip4: yes
	do-ip6: no

	# Mapeamento de Zonas e Registros ===
	local-zone: "dns.internal." static
	local-zone: "dns.domestico." static

	# Registros da Subnet 172.31.2.0/16
	local-data: "pc-server.dns.internal. IN A 172.31.2.1"
	local-data: "pc-desktop.dns.internal. IN A 172.31.2.2"
	local-data: "server.dns.internal. IN CNAME pc-server.dns.internal."
	local-data: "desktop.dns.internal. IN CNAME pc-desktop.dns.internal."

	# Registros da Subnet 192.168.1.0/24
	local-data: "a16.dns.domestico. IN A 192.168.1.10"

	# Ativação do controle por CLI
remote-control:
	control-enable: yes
	control-interface: 127.0.0.1
	control-port: 8953
	server-key-file: "/etc/unbound/unbound_server.key"
	server-cert-file: "/etc/unbound/unbound_server.pem"
	control-key-file: "/etc/unbound/unbound_control.key"
	control-cert-file: "/etc/unbound/unbound_control.pem"
