# ==========================================
# Configuração de Servidor DNS com Unbound !
# ==========================================
server:
  # === Detalhamento dos logs ===
  # -- Nível 1 apenas registra erros.
    verbosity: 1
  # === Interface de rede ===
  # -- Escutar em todas as interfaces de rede
    interface: 0.0.0.0
  # === Segurança do Servidor DNS ===
  # -- Quem pode consultar o servidor
    access-control: 172.31.0.0/16 allow
    access-control: 192.168.1.0/24 allow
    access-control: 127.0.0.0/8 allow
  # === Zonas de Domínios ===
  # -- Criar as zonas e os domínios
    local-zone: "dns.teste.local." static
    local-zone: "android.local." static
  # === REGISTROS "dns.teste.local" ===
  # -- Registro do Servidor
    local-data: "PC-Server.dns.teste.local. IN A 172.31.2.1"
    local-data: "Server.dns.teste.local. IN CNAME PC-Server.dns.teste.local."
  # -- Registro do Desktop
    local-data: "PC-Desktop.dns.teste.local. IN A 172.31.2.2"
    local-data: "Desktop.dns.teste.local. IN CNAME PC-Desktop.dns.teste.local."
  # === REGISTROS "android.local." ===
    local-data: "A16.android.local. IN A 192.168.1.10"
